server:
  port: 8080

spring:
  application:
    name: donkeykong-db
  h2:
    console:
      enabled: true
  datasource:
    url: ${DONKEYKONG_SCORE_DB_URL:jdbc:h2:file:./db/score-db;AUTO_SERVER=TRUE}
    username: sa
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
