server:
  port: 8082

spring:
  application:
    name: donkeykong-db
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/score-db
    username: sa
    driverClassName: org.h2.Driver

  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database.action: create
