spring.application.name=catering-app

spring.datasource.url=jdbc:oracle:thin:@bayer.cs.vsb.cz:1521:oracle
spring.datasource.username=ZAM0074
spring.datasource.password=osVSOwCvA6yO96Ao
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.sql.init.mode=never
spring.sql.init.platform=oracle
spring.sql.init.schema-locations=classpath:schema-oracle.sql
spring.sql.init.data-locations=classpath:data-oracle.sql
spring.sql.init.continue-on-error=false

spring.thymeleaf.cache=false
server.error.include-message=always
