CREATE TABLE roles (
    role_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(30) NOT NULL,
    can_manage_users NUMBER(1) DEFAULT 0 NOT NULL,
    can_manage_projects NUMBER(1) DEFAULT 0 NOT NULL,
    can_publish NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_roles_name CHECK (name IN ('manager', 'editor')),
    CONSTRAINT chk_roles_can_manage_users CHECK (can_manage_users IN (0, 1)),
    CONSTRAINT chk_roles_can_manage_projects CHECK (can_manage_projects IN (0, 1)),
    CONSTRAINT chk_roles_can_publish CHECK (can_publish IN (0, 1))
);

CREATE TABLE users (
    user_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id NUMBER(19) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(role_id),
    CONSTRAINT chk_users_is_active CHECK (is_active IN (0, 1))
);

CREATE TABLE projects (
    project_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    event_date DATE,
    guest_count NUMBER(10),
    status VARCHAR2(30) NOT NULL,
    created_by NUMBER(19) NOT NULL,
    active_version_id NUMBER(19),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT chk_projects_status CHECK (status IN ('draft', 'sent', 'approved', 'archived'))
);

CREATE TABLE project_collaborators (
    project_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    role_in_project VARCHAR2(30) NOT NULL,
    added_by NUMBER(19) NOT NULL,
    added_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_project_collaborators PRIMARY KEY (project_id, user_id),
    CONSTRAINT fk_pc_project FOREIGN KEY (project_id) REFERENCES projects(project_id),
    CONSTRAINT fk_pc_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_pc_added_by FOREIGN KEY (added_by) REFERENCES users(user_id),
    CONSTRAINT chk_pc_role CHECK (role_in_project IN ('manager', 'editor'))
);

CREATE TABLE menus (
    menu_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id NUMBER(19) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    created_by NUMBER(19) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_menus_project FOREIGN KEY (project_id) REFERENCES projects(project_id),
    CONSTRAINT fk_menus_created_by FOREIGN KEY (created_by) REFERENCES users(user_id)
);

CREATE TABLE templates (
    template_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    font VARCHAR2(255),
    background_image VARCHAR2(2048),
    style_json CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE menu_versions (
    version_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id NUMBER(19) NOT NULL,
    template_id NUMBER(19),
    version_number NUMBER(10) NOT NULL,
    with_prices NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_mv_menu FOREIGN KEY (menu_id) REFERENCES menus(menu_id),
    CONSTRAINT fk_mv_template FOREIGN KEY (template_id) REFERENCES templates(template_id),
    CONSTRAINT chk_mv_with_prices CHECK (with_prices IN (0, 1))
);

ALTER TABLE projects
    ADD CONSTRAINT fk_projects_active_version
    FOREIGN KEY (active_version_id)
    REFERENCES menu_versions(version_id);

CREATE TABLE sections (
    section_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id NUMBER(19) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    display_order NUMBER(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_sections_version FOREIGN KEY (version_id) REFERENCES menu_versions(version_id)
);

CREATE TABLE items (
    item_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    description CLOB,
    category VARCHAR2(255),
    price NUMBER(12, 2),
    dph NUMBER(5, 2),
    allergens VARCHAR2(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE menu_items (
    menu_item_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id NUMBER(19) NOT NULL,
    item_id NUMBER(19) NOT NULL,
    servings_per_person NUMBER(8, 2),
    price_at_version NUMBER(12, 2),
    display_order NUMBER(10) NOT NULL,
    notes CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_menu_items_section FOREIGN KEY (section_id) REFERENCES sections(section_id),
    CONSTRAINT fk_menu_items_item FOREIGN KEY (item_id) REFERENCES items(item_id)
);

