"""email rename

Revision ID: 1cf06f88718f
Revises: 13aec34b80fc
Create Date: 2026-04-13 09:28:49.451630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf06f88718f'
down_revision: Union[str, Sequence[str], None] = '13aec34b80fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as op_batch:
        op_batch.alter_column('email', new_column_name = 'email_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as op_batch:
        op_batch.alter_column('email_address', new_column_name = 'email')
    # ### end Alembic commands ###
